### PR TITLE
Update link to make them Obsidian compatible

### LINKED ISSUE #6: Internal Links
Hey, thank you for developing this plug-in!!
Have you planned to integrate obsidian links into the diagrams? 

I currently use mermaid, what is great but integrating obsidian links is cumbersome and the layout options are more limited. 
Having fast internal link options to integrate with diagrams would open up new workflows currently not possible, at least for me. 
Best regards!

### PR DESCRIPTION
**Pull request by Portevent**
fix #6

### CODE REVIEW

**Comment by berniexie** [comment]
@Portevent typescript is failing, can you fix the errors please?

**Comment by berniexie** [comment]
@Portevent so right now we can link either to an internal page or an external link. If we add your code in, I think external links break. I wonder if there's a way to see if the link matches an internal doc and if not, keep it as an external link?

**Comment by alixander** [comment]
@berniexie why would external links break? this is just adding extra attributes, not changing any afaik.

But yes, there should be a way to identify external links: the presence of URL protocols. https://developer.mozilla.org/en-US/docs/Web/API/URL/protocol

What if users want to link to other resources though that are neither external nor Obsidian pages? Like a local PDF or image? `/home/mycat.pdf`. We should test that those work, if they were working before.

**Comment by berniexie** [comment]
local links were not working before

**Review by berniexie — APPROVED** [review]

**Comment by berniexie** [comment]
@Portevent Looks good to me, thanks for the change!

**Comment by berniexie** [comment]
@Portevent
This commit "Fix typescript & only apply modification to internal link" is unsigned though, can u fix that please

**Review by berniexie — CHANGES_REQUESTED** [review]
@Portevent
Changes look good to me, made some small tweaks. However, the commit "Fix typescript & only apply modification to internal link" is unsigned though, can u fix that please

**Comment by korniychuk** [comment]
Really waiting for this PR delivered 🙏

**Review by gavin-ts — APPROVED** [review]
rebased to resolve conflicts + sign the unsigned commit

**Pull request merged**
