### PR TITLE
add example gif to README

### PR DESCRIPTION
**Pull request by berniexie**

### CODE REVIEW

**Review by alixander — CHANGES_REQUESTED** [review]
add it to the docs/assets

**Comment by berniexie** [comment]
Why is anmol's version ok https://github.com/terrastruct/d2/pull/319

**Comment by alixander** [comment]
@nhooyr should use the docs version too. i don't even know the workflow of updating this img, i have to use the github UI or like copy paste the url.

**Comment by berniexie** [comment]
@alixander yeah i don't think there's a way to embed a static video in markdown. Its either a linked mp4 or a gif.

**Comment by alixander** [comment]
what's the difference between a "static video" and a "linked mp4"

**Comment by berniexie** [comment]
a static video is a video asset that we upload to the repository. There's no way to embed that into the Github markdown. a linked mp4 or a linked video is what we have now, something that is a link to the githubusercontent url

**Comment by alixander** [comment]
ohh i see. lame. okay then

**Review by alixander — APPROVED** [review]
nice video lol

**Comment by nhooyr** [comment]
tbh regardless a video is too big, i don't think it belongs in the repo. it just makes us tend to compress it and ruin all quality.

**Comment by alixander** [comment]
mm good point actually

**Comment by nhooyr** [comment]
Like this one looks like ass to me because of how much it was downscaled. Blurry as shit. @berniexie please redo and don't downscale, videos stream so it's not a big deal as long as we don't put it directly into the repo. ofc still make it an mp4.

i've been using ffmpeg:

```
ffmpeg -i /Users/nhooyr/Movies/d2.mov -filter:v "setpts=PTS/1.3" /Users/nhooyr/Movies/d2.mp4
```

d2.mov being the example I recorded with macOS's builtin screen recorder. setpts/1.3 speeds it up by a factor of 1.3. remove it if you don't need your video sped up.

**Comment by nhooyr** [comment]
The text is also much much too small. Not everyone uses a giant monitor like you guys. Increase your font size, zoom in your editor or adjust your display scaling so it looks good on a narrower display. Like compare the video I made vs the gif that alex made that's on the d2 readme right now. Massive difference in readablity when you're on a laptop.

**Pull request merged**
